### ISSUE TITLE
Navbar is breaking at a certain view port

### ISSUE THREAD

**Issue by Athrav04** [Athrav04/IEEE-Web#5]
The nav bar and the website is breaking at a certain viewport (768px X 757px) 
after this breakpoint navbar does not work as expected and all the contents overflow 
<img width="921" alt="Screenshot 2024-10-07 at 10 48 18 PM" src="https://github.com/user-attachments/assets/3adc2133-bdbe-4740-a2d3-86d04ba1bcd7">

<img width="432" alt="Screenshot 2024-10-07 at 10 52 18 PM" src="https://github.com/user-attachments/assets/9c234138-fa39-40fd-a80b-3b457f70155c">

**Comment by CK-Check** [comment]
I haven't yet made it compatible with the phones.

**Comment by Athrav04** [comment]
try making it
